language: python
python: "3.6"

# whitelist
branches:
  only:
    - master

before_install:
  - pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
  - pip install tqdm
  - pip install pyyaml
  - pip install tensorboardX

sudo: false

install: true

before_script:
  - cp ./unittest/run_all_test.sh .

script:
  - bash run_all_test.sh