data_configs:
  lang_pair: "zh-en"
  train_data:
    - "./unittest/data/train/zh.under50.txt"
    - "./unittest/data/train/en.under50.txt"
  valid_data:
    - "./unittest/data/dev/zh.0"
    - "./unittest/data/dev/en.0"
  bleu_valid_reference: "./unittest/data/dev/en."
  dictionaries:
    - "./unittest/data/dict/dict.zh.json"
    - "./unittest/data/dict/dict.en.json"
  bpe_codes:
    - ""
    - ""
  use_char:
    - false
    - false
  n_words:
    - 501
    - 502
  max_len:
    - 20
    - 20
  num_refs: 4
  eval_at_char_level: false

model_configs:
  model: Transformer
  n_layers: 2
  n_head: 3
  d_word_vec: 24
  d_model: 24
  d_inner_hid: 17
  dropout: 0.1
  n_max_seq: 100
  proj_share_weight: true
  bridge_type: zero
  label_smoothing: 0.1

optimizer_configs:
  optimizer: "adam"
  learning_rate: 2.0
  grad_clip: 0.0
  optimizer_params: ~ # other arguments for optimizer.
  schedule_method: noam
  scheduler_configs:
    d_model: 24
    warmup_steps: 8000
    schedule_freq: 1

training_configs:
  seed: 1234
  max_epochs: 2
  shuffle: false
  use_bucket: true # Whether to use bucket. If true, model will run faster while a little bit performance regression.
  buffer_size: 100 # Only valid when use_bucket is true.
  batch_size: 10
  batching_key: "samples"
  update_cycle: -1
  shard_size: -1
  valid_batch_size: 100
  bleu_valid_batch_size: 3
  bleu_valid_max_steps: 10
  bleu_valid_warmup: 10000
  bleu_valid_configs:
    bleu_script: "multi-bleu"
    lowercase: true
    postprocess: false
  disp_freq: 100
  save_freq: 1000
  keep_checkpoint_max: 1
  loss_valid_freq: &decay_freq 10
  bleu_valid_freq: 100
  early_stop_patience: 20