data_configs:
  lang_pair: "zh-en"
  train_data:
    - "./unittests/data/train/zh.under50.txt"
    - "./unittests/data/train/en.under50.txt"
  valid_data:
    - "./unittests/data/dev/zh.0"
    - "./unittests/data/dev/en.0"
  bleu_valid_reference: "./unittests/data/dev/en."
  vocabularies:
    - type: "word"
      dict_path: "./unittests/data/dict/dict.zh.json"
      max_n_words: 501
    - type: "word"
      dict_path: "./unittests/data/dict/dict.en.json"
      max_n_words: 502
  max_len:
    - 20
    - 20
  num_refs: 4
  eval_at_char_level: false

model_configs:
  model: Transformer
  n_layers: 2
  n_head: 3
  dim_per_head: 7
  d_word_vec: 24
  d_model: 24
  d_inner_hid: 17
  dropout: 0.1
  n_max_seq: 100
  proj_share_weight: true
  bridge_type: zero
  label_smoothing: 0.1

optimizer_configs:
  optimizer: "adam"
  learning_rate: 2.0
  grad_clip: 0.0
  optimizer_params: ~ # other arguments for optimizer.
  schedule_method: noam
  scheduler_configs:
    d_model: 24
    warmup_steps: 8000

training_configs:
  seed: 1234
  max_epochs: 2
  shuffle: false
  use_bucket: true # Whether to use bucket. If true, model will run faster while a little bit performance regression.
  buffer_size: 100 # Only valid when use_bucket is true.
  batch_size: 100
  batching_key: "tokens"
  update_cycle: 2
  valid_batch_size: 100
  disp_freq: 100
  save_freq: 1
  num_kept_checkpoints: 100
  loss_valid_freq: &decay_freq 10
  bleu_valid_freq: 100
  bleu_valid_batch_size: 3
  bleu_valid_warmup: 1
  bleu_valid_configs:
    max_steps: 10
    beam_size: 5
    alpha: 0.6
    sacrebleu_args: "--tokenize none -lc"
    postprocess: false
  early_stop_patience: 20
  moving_average_method: "sma"
  moving_average_start_epoch: 1